@startuml
!define INTERFACE interface

card card [
    1. Поключение к клиенту (IClientHandler)
    2. Выбор xml файла (IDataProcessor)
    3. Парсинг xml файла (IParser)
    4. Отправка данных клиенту (IResponseSender)
    
    Server > IClientHandler > IDataProcessor > IParser > IParsedData > IResponseSender 
]

INTERFACE IServer{
    + Run()
    + Stop()
    }
    
INTERFACE IClientHandler {
  + Handle()
  + GetClients()
  + GetClient(ip?)
  --
  Отвечает за подключение к клиенту,
  хранение клиентов 
    
}
  
INTERFACE IDataProcessor {
  + Process()
  --
  Отвечает за выбор xml файла
  (зависит от интерфейса взаимодействия)
}

INTERFACE IParser {
  + Parse()
  --
  Отвечает за парсинг xml файла
}

INTERFACE IParsedData {
  + GetFrom()
  + GetText()
  + GetColor()
  + GetImage()
}

INTERFACE IResponseSender {
  + Send(data : IParsedData)
}

CLASS Server {
    + Run()
    + Stop()
  
  --
  Агригирует все интерфейсы для работы
  с клиентом, обработки и отправки данных
  
}

IServer <|.. Server
Server o-- IClientHandler
Server o-- IDataProcessor
Server o-- IParser

IParser *-- IParsedData

IDataProcessor -right-> IParser
IParser -right-> IResponseSender


IResponseSender <.. IClientHandler : "Тип подключения (вашем случае TCP)"
 

@enduml